# Van der Pol Oscillator Environment Configuration
# System: ẍ - μ(1-x²)ẋ + x = u

environment:
  name: "van_der_pol"
  description: "Van der Pol oscillator with nonlinear dynamics"
  
  # System dynamics: ẍ - μ(1-x²)ẋ + x = u
  # State: [position, velocity] 
  # Control: force input (u)
  
  # State bounds: [position_bounds, velocity_bounds]
  state_bounds:
    - [-2.0, 2.0]  # Position bounds
    - [-2.0, 2.0]  # Velocity bounds
  
  # Control bounds
  control_bounds: [-5.0, 5.0]  # Force bounds
  
  # Initial condition sampling bounds
  initial_bounds:
    - [-1.5, 1.5]  # Initial position
    - [-1.5, 1.5]  # Initial velocity
  
  # Van der Pol parameter
  mu: 1.0  # Damping parameter
  
  # Solver configuration for nonlinear optimization
  solver_config:
    Q: [10.0, 5.0]  # State weights [position, velocity]
    R: 0.1          # Control weight
    maxiter: 1000   # Maximum solver iterations

# Environment-specific training overrides
training:
  # Van der Pol might need different training settings due to nonlinearity
  sft:
    # Could use more epochs due to complexity
    num_train_epochs: 6
  grpo:
    # Might need more GRPO steps for nonlinear system
    max_steps: 150

# Environment-specific data generation
data:
  # Van der Pol might need more samples due to nonlinearity
  samples_per_training: 400
  # Add more diverse initial conditions for nonlinear system
  diverse_sampling: true